typography_spectrum: 0.9944204788189381
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.22807816206477582
  lightness: 0.85740394028835
  saturation: 0.1758721941150725
  rhythmicContrast: 0.6839737256523222
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9956770653370768
analytics:
  google: null
  facebook: null
  twitter: null
name: MitchSantell
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: BehindTheGreenGlass
purpose: []
